ALTER TABLE "companies"
ADD COLUMN IF NOT EXISTS "review_notes" TEXT,
ADD COLUMN IF NOT EXISTS "reviewed_by" UUID,
ADD COLUMN IF NOT EXISTS "reviewed_at" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "submitted_at" TIMESTAMPTZ;